=== MaxVell220/Blinov_Tasks/5. XML_variant_11/Tourist_voucher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:complexType name="newAgency">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="tourist_voucher" type="tourist_voucher"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tourist_voucher">
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:sequence>
      <xs:element name="type" type="type"/>
      <xs:element name="country" type="xs:string"/>
      <xs:element name="days" type="xs:positiveInteger"/>

      <xs:element name="transport" type="transport"/>
      <xs:element name="cost" type="xs:double"/>
      <xs:element name="hotel">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="numberOfStarts" type="xs:positiveInteger"/>
            <xs:element name="isMealsIncluded" type="xs:boolean"/>
            <xs:element name="meals" type="meals"/>
            <xs:element name="numberOfRooms" type="xs:positiveInteger"/>
            <xs:element name="isTvIncluded" type="xs:boolean"/>
            <xs:element name="isAirConditioningIncluded" type="xs:boolean"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="agency" type="newAgency"/>

  <xs:simpleType name="type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="holiday_tour"/>
      <xs:enumeration value="excursion"/>
      <xs:enumeration value="pilgrimage"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="days">
    <xs:restriction base="xs:positiveInteger">
      <xs:maxInclusive value="30"/>
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="transport">
    <xs:restriction base="xs:string">
      <xs:enumeration value="car"/>
      <xs:enumeration value="train"/>
      <xs:enumeration value="plane"/>
      <xs:enumeration value="ship"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="cost">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="numberOfStarts">
    <xs:restriction base="xs:positiveInteger">
      <xs:maxInclusive value="5"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="meals">
    <xs:restriction base="xs:string">
      <xs:enumeration value="HB"/>
      <xs:enumeration value="BB"/>
      <xs:enumeration value="Al"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="numberOfRooms">
    <xs:restriction base="xs:positiveInteger">
      <xs:maxInclusive value="5"/>
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== MaxVell220/Blinov_Tasks/5. XML_variant_11/Tourist_voucher.xml
<?xml version="1.0" encoding="UTF-8"?>
<agency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  name="Travel With Me"
  xsi:noNamespaceSchemaLocation="Tourist_voucher.xsd">
  <tourist_voucher id="ere3y1">
    <cost>899.9</cost>
    <country>Egypt</country>
    <days>10</days>
    <hotel>
      <isAirConditioningIncluded>true</isAirConditioningIncluded>
      <isMealsIncluded>true</isMealsIncluded>
      <isTvIncluded>true</isTvIncluded>
      <meals>Al</meals>
      <numberOfRooms>3</numberOfRooms>
      <numberOfStarts>4</numberOfStarts>
    </hotel>
    <transport>plane</transport>
    <type>holiday_tour</type>
  </tourist_voucher>
  <tourist_voucher id="ere3y2">
    <cost>299.9</cost>
    <country>Poland</country>
    <days>5</days>
    <hotel>
      <isAirConditioningIncluded>false</isAirConditioningIncluded>
      <isMealsIncluded>true</isMealsIncluded>
      <isTvIncluded>true</isTvIncluded>
      <meals>BB</meals>
      <numberOfRooms>2</numberOfRooms>
      <numberOfStarts>3</numberOfStarts>
    </hotel>
    <transport>car</transport>
    <type>excursion</type>
  </tourist_voucher>
  <tourist_voucher id="ere3y3">
    <cost>1399.9</cost>
    <country>Spain</country>
    <days>21</days>
    <hotel>
      <isAirConditioningIncluded>false</isAirConditioningIncluded>
      <isMealsIncluded>true</isMealsIncluded>
      <isTvIncluded>true</isTvIncluded>
      <meals>HB</meals>
      <numberOfRooms>1</numberOfRooms>
      <numberOfStarts>2</numberOfStarts>
    </hotel>
    <transport>plane</transport>
    <type>pilgrimage</type>
  </tourist_voucher>
  <tourist_voucher id="ere3y4">
    <cost>2199.9</cost>
    <country>USA</country>
    <days>30</days>
    <hotel>
      <isAirConditioningIncluded>true</isAirConditioningIncluded>
      <isMealsIncluded>true</isMealsIncluded>
      <isTvIncluded>true</isTvIncluded>
      <meals>Al</meals>
      <numberOfRooms>2</numberOfRooms>
      <numberOfStarts>3</numberOfStarts>
    </hotel>
    <transport>ship</transport>
    <type>holiday_tour</type>
  </tourist_voucher>
</agency>
